import { LineChartData } from '@core/models';

export const GithubStarHistoryAreaChartTemplate1 = (
  id: string,
  name: string,
  description: string,
  data: LineChartData[]
) => {
  return {
    'canvas-background-layer': {
      layerComponent: 'CanvasSquareAnnotationLayer',
      settingSet: {
        General: [
          'CanvasLayerGeneralSetting',
          'CanvasLayerBackgroundSetting',
          'CanvasLayerContainerSetting',
        ],
      },
      id: 'canvas-background-layer',
      name: 'Background',
      height: 932,
      width: 1657,
      x: 0,
      y: 0,
      background: {
        type: 'gradient-background',
        value: 'linear-gradient(135deg, #402662, #3900a6)',
      },
      draggable: false,
      resizable: true,
      deletable: false,
      hideable: false,
      editable: true,
      rotatable: false,
      duplicatable: false,
      type: 'canvas',
      lockAspectRatio: true,
    },
    [id]: {
      layerComponent: 'CanvasLineChartLayer',
      settingSet: {
        General: [
          'CanvasLayerOrderSetting',
          'CanvasLayerGeneralSetting',
          'CanvasLayerBackgroundSetting',
          'CanvasLayerContainerSetting',
        ],
        Chart: [
          'CanvasLayerGeneralChartSetting',
          'CanvasChartAxisSetting',
          'CanvasLayerLineChartSetting',
        ],
      },
      type: 'line-chart',
      background: {
        type: 'solid-background',
        value: '#fefefe',
      },
      cssStyles: {
        borderRadius: 30,
        overflow: 'hidden',
        boxShadow:
          'rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px',
        borderWidth: 5,
        borderColor: '#001a51',
      },
      height: 689.3333333333334,
      width: 1254.6666666666667,
      x: 136.83938598632812,
      y: 87.69767761230469,
      id,
      name,
      deletable: true,
      draggable: true,
      resizable: true,
      editable: true,
      rotatable: true,
      hideable: true,
      duplicatable: true,
      extra: {
        labelShown: false,
        lineStrokeStyle: {
          strokeWidth: 2,
          backgroundColor: '#664437',
          color: '#664437',
        },
        editLabelPosition: false,
        editSubjectPosition: false,
        subjectType: 'circle',
        connectorType: 'elbow',
        annotationPosition: {
          x: 279.55658816006707,
          y: 206.752688172043,
          dx: -150,
          dy: -100,
        },
        annotationTitle: 'Title',
        annotationTitleStyle: {
          fontSize: 25,
        },
        annotationSubtitle: 'Example of the line chart subtitle',
        annotationSubtitleStyle: {
          fontSize: 20,
        },
        annotationContainerStyle: {
          background: 'white',
          border: '1px solid #e9e9e9',
          boxShadow:
            'rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px',
          borderRadius: 10,
          color: 'rgb(135, 135, 135)',
          fontSize: '0.8em',
          lineHeight: '20px',
          padding: '0 0.4em 0 1em',
          fontWeight: 200,
        },
        annotationContainerWidth: 200,
        columns: {
          xAxis: {
            fieldName: 'X Axis',
            dataType: 'DATE',
          },
          yAxis: {
            fieldName: 'Y Axis',
            dataType: 'NUMBER',
          },
        },
        data,
        areaMode: true,
        axisStyle: {
          fontFamily: 'Inter',
        },
        gridColumnsMode: true,
        areaStyle: {
          backgroundColor: '#2d265b',
        },
        lineCurve: true,
      },
      parentId: 'canvas-background-layer',
      childSet: {
        [`${id}:title`]: {
          layerComponent: 'CanvasTextAnnotationLayer',
          settingSet: {
            General: [
              'CanvasLayerOrderSetting',
              'CanvasLayerGeneralSetting',
              'CanvasLayerBackgroundSetting',
              'CanvasLayerContainerSetting',
            ],
            Font: ['CanvasLayerFontFamilySetting', 'CanvasLayerFontStyleSetting'],
          },
          id: `${id}:title`,
          background: {
            type: 'transparent-background',
          },
          deletable: false,
          draggable: false,
          resizable: true,
          editable: true,
          hideable: true,
          rotatable: true,
          duplicatable: true,
          height: 70,
          width: 600,
          name: `${name} - Title`,
          type: 'text-annotation',
          extra: {
            value: name,
            fontStyle: {
              margin: 0,
              fontSize: 30,
              color: 'rgb(0, 0, 0)',
              fontWeight: 'bold',
            },
          },
          parentId: id,
        },
        [`${id}:subtitle`]: {
          layerComponent: 'CanvasTextAnnotationLayer',
          settingSet: {
            General: [
              'CanvasLayerOrderSetting',
              'CanvasLayerGeneralSetting',
              'CanvasLayerBackgroundSetting',
              'CanvasLayerContainerSetting',
            ],
            Font: ['CanvasLayerFontFamilySetting', 'CanvasLayerFontStyleSetting'],
          },
          id: `${id}:subtitle`,
          background: {
            type: 'transparent-background',
          },
          deletable: false,
          draggable: false,
          resizable: true,
          editable: true,
          hideable: true,
          rotatable: true,
          duplicatable: true,
          height: 50,
          width: 600,
          name: `${name} - Subtitle`,
          type: 'text-annotation',
          extra: {
            value: description,
            fontStyle: {
              margin: 0,
              fontSize: 20,
              color: 'rgb(135, 135, 135)',
            },
          },
          parentId: id,
        },
      },
    },
  };
};

export const GithubStarHistoryAreaChartTemplate2 = (
  id: string,
  name: string,
  description: string,
  data: LineChartData[]
) => ({
  'canvas-background-layer': {
    layerComponent: 'CanvasSquareAnnotationLayer',
    settingSet: {
      General: [
        'CanvasLayerGeneralSetting',
        'CanvasLayerBackgroundSetting',
        'CanvasLayerContainerSetting',
      ],
    },
    id: 'canvas-background-layer',
    name: 'Background',
    height: 932,
    width: 1657,
    x: 0,
    y: 0,
    background: {
      type: 'mesh-gradient-background',
      value: {
        backgroundColor: 'hsl(235, 100%, 74%)',
        backgroundImage:
          'radial-gradient(at 0% 0%, hsl(235, 100%, 74%) 0px, transparent 55%)\n,radial-gradient(at 98% 4%, hsl(265, 100%, 65.75%) 0px, transparent 55%)\n,radial-gradient(at 17% 44%, hsl(175, 100%, 60.5%) 0px, transparent 55%)\n,radial-gradient(at 90% 66%, hsl(280, 100%, 69.25%) 0px, transparent 55%)\n,radial-gradient(at 98% 52%, hsl(175, 100%, 57%) 0px, transparent 55%)\n,radial-gradient(at 0% 99%, hsl(385, 100%, 72.25%) 0px, transparent 55%)\n',
      },
    },
    draggable: false,
    resizable: true,
    deletable: false,
    hideable: false,
    editable: true,
    rotatable: false,
    duplicatable: false,
    type: 'canvas',
    lockAspectRatio: true,
  },
  [id]: {
    layerComponent: 'CanvasLineChartLayer',
    settingSet: {
      General: [
        'CanvasLayerOrderSetting',
        'CanvasLayerGeneralSetting',
        'CanvasLayerBackgroundSetting',
        'CanvasLayerContainerSetting',
      ],
      Chart: [
        'CanvasLayerGeneralChartSetting',
        'CanvasChartAxisSetting',
        'CanvasLayerLineChartSetting',
      ],
    },
    type: 'line-chart',
    background: {
      type: 'solid-background',
      value: '#fefefe',
    },
    cssStyles: {
      borderRadius: 30,
      overflow: 'hidden',
      boxShadow:
        'rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px',
      borderWidth: 5,
      borderColor: '#001a51',
    },
    height: 689.3333333333334,
    width: 1254.6666666666667,
    x: 136.83938598632812,
    y: 87.69767761230469,
    id,
    name,
    deletable: true,
    draggable: true,
    resizable: true,
    editable: true,
    rotatable: true,
    hideable: true,
    duplicatable: true,
    extra: {
      labelShown: false,
      lineStrokeStyle: {
        strokeWidth: 2,
        backgroundColor: '#664437',
        color: '#664437',
      },
      editLabelPosition: false,
      editSubjectPosition: false,
      subjectType: 'circle',
      connectorType: 'elbow',
      annotationPosition: {
        x: 278.59200248444955,
        y: 206.752688172043,
        dx: -150,
        dy: -100,
      },
      annotationTitle: 'Title',
      annotationTitleStyle: {
        fontSize: 25,
      },
      annotationSubtitle: 'Example of the line chart subtitle',
      annotationSubtitleStyle: {
        fontSize: 20,
      },
      annotationContainerStyle: {
        background: 'white',
        border: '1px solid #e9e9e9',
        boxShadow:
          'rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px',
        borderRadius: 10,
        color: 'rgb(135, 135, 135)',
        fontSize: '0.8em',
        lineHeight: '20px',
        padding: '0 0.4em 0 1em',
        fontWeight: 200,
      },
      annotationContainerWidth: 200,
      columns: {
        xAxis: {
          fieldName: 'X Axis',
          dataType: 'DATE',
        },
        yAxis: {
          fieldName: 'Y Axis',
          dataType: 'NUMBER',
        },
      },
      data,
      areaMode: true,
      axisStyle: {
        fontFamily: 'Inter',
      },
      gridColumnsMode: true,
      areaStyle: {
        backgroundColor: '#7d6ce8',
      },
      lineCurve: true,
    },
    parentId: 'canvas-background-layer',
    childSet: {
      [`${id}:title`]: {
        layerComponent: 'CanvasTextAnnotationLayer',
        settingSet: {
          General: [
            'CanvasLayerOrderSetting',
            'CanvasLayerGeneralSetting',
            'CanvasLayerBackgroundSetting',
            'CanvasLayerContainerSetting',
          ],
          Font: ['CanvasLayerFontFamilySetting', 'CanvasLayerFontStyleSetting'],
        },
        id: `${id}:title`,
        background: {
          type: 'transparent-background',
        },
        deletable: false,
        draggable: false,
        resizable: true,
        editable: true,
        hideable: true,
        rotatable: true,
        duplicatable: true,
        height: 70,
        width: 600,
        name: `${name} - Title`,
        type: 'text-annotation',
        extra: {
          value: name,
          fontStyle: {
            margin: 0,
            fontSize: 30,
            color: 'rgb(0, 0, 0)',
            fontWeight: 'bold',
          },
        },
        parentId: id,
      },
      [`${id}:subtitle`]: {
        layerComponent: 'CanvasTextAnnotationLayer',
        settingSet: {
          General: [
            'CanvasLayerOrderSetting',
            'CanvasLayerGeneralSetting',
            'CanvasLayerBackgroundSetting',
            'CanvasLayerContainerSetting',
          ],
          Font: ['CanvasLayerFontFamilySetting', 'CanvasLayerFontStyleSetting'],
        },
        id: `${id}:subtitle`,
        background: {
          type: 'transparent-background',
        },
        deletable: false,
        draggable: false,
        resizable: true,
        editable: true,
        hideable: true,
        rotatable: true,
        duplicatable: true,
        height: 50,
        width: 600,
        name: `${name} - Subtitle`,
        type: 'text-annotation',
        extra: {
          value: description,
          fontStyle: {
            margin: 0,
            fontSize: 20,
            color: 'rgb(135, 135, 135)',
          },
        },
        parentId: id,
      },
    },
  },
});

export const GithubStarHistoryAreaChartTemplate3 = (
  id: string,
  name: string,
  description: string,
  data: LineChartData[]
) => ({
  'canvas-background-layer': {
    layerComponent: 'CanvasSquareAnnotationLayer',
    settingSet: {
      General: [
        'CanvasLayerGeneralSetting',
        'CanvasLayerBackgroundSetting',
        'CanvasLayerContainerSetting',
      ],
    },
    id: 'canvas-background-layer',
    name: 'Background',
    height: 932,
    width: 1657,
    x: 0,
    y: 0,
    background: {
      type: 'gradient-background',
      value: 'linear-gradient(135deg, #402565, #30be96)',
    },
    draggable: false,
    resizable: true,
    deletable: false,
    hideable: false,
    editable: true,
    rotatable: false,
    duplicatable: false,
    type: 'canvas',
    lockAspectRatio: true,
  },
  [id]: {
    layerComponent: 'CanvasLineChartLayer',
    settingSet: {
      General: [
        'CanvasLayerOrderSetting',
        'CanvasLayerGeneralSetting',
        'CanvasLayerBackgroundSetting',
        'CanvasLayerContainerSetting',
      ],
      Chart: [
        'CanvasLayerGeneralChartSetting',
        'CanvasChartAxisSetting',
        'CanvasLayerLineChartSetting',
      ],
    },
    type: 'line-chart',
    background: {
      type: 'solid-background',
      value: '#242424',
    },
    cssStyles: {
      borderRadius: 30,
      overflow: 'hidden',
      boxShadow:
        'rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px',
      borderWidth: 5,
      borderColor: '#000000',
    },
    height: 689.3333333333334,
    width: 1254.6666666666667,
    x: 66.9515380859375,
    y: 37.000762939453125,
    id,
    name: 'nomadiz/edma',
    deletable: true,
    draggable: true,
    resizable: true,
    editable: true,
    rotatable: true,
    hideable: true,
    duplicatable: true,
    extra: {
      labelShown: false,
      lineStrokeStyle: {
        strokeWidth: 2,
        backgroundColor: '#664437',
        color: '#664437',
      },
      editLabelPosition: false,
      editSubjectPosition: false,
      subjectType: 'circle',
      connectorType: 'elbow',
      annotationPosition: {
        x: 320.2572914943711,
        y: 201.26881720430106,
        dx: -150,
        dy: -100,
      },
      annotationTitle: 'Title',
      annotationTitleStyle: {
        fontSize: 25,
      },
      annotationSubtitle: 'Example of the line chart subtitle',
      annotationSubtitleStyle: {
        fontSize: 20,
      },
      annotationContainerStyle: {
        background: 'white',
        border: '1px solid #e9e9e9',
        boxShadow:
          'rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px',
        borderRadius: 10,
        color: 'rgb(135, 135, 135)',
        fontSize: '0.8em',
        lineHeight: '20px',
        padding: '0 0.4em 0 1em',
        fontWeight: 200,
      },
      annotationContainerWidth: 200,
      columns: {
        xAxis: {
          fieldName: 'X Axis',
          dataType: 'DATE',
        },
        yAxis: {
          fieldName: 'Y Axis',
          dataType: 'NUMBER',
        },
      },
      data,
      areaMode: true,
      axisStyle: {
        fontFamily: 'Inter',
        color: '#ffffff',
        stroke: '#2be63b',
      },
      gridColumnsMode: true,
      areaStyle: {
        backgroundColor: '#6ce8b7',
      },
      lineCurve: true,
    },
    parentId: 'canvas-background-layer',
    childSet: {
      [`${id}:title`]: {
        layerComponent: 'CanvasTextAnnotationLayer',
        settingSet: {
          General: [
            'CanvasLayerOrderSetting',
            'CanvasLayerGeneralSetting',
            'CanvasLayerBackgroundSetting',
            'CanvasLayerContainerSetting',
          ],
          Font: ['CanvasLayerFontFamilySetting', 'CanvasLayerFontStyleSetting'],
        },
        id: `${id}:title`,
        background: {
          type: 'transparent-background',
        },
        deletable: false,
        draggable: false,
        resizable: true,
        editable: true,
        hideable: true,
        rotatable: true,
        duplicatable: true,
        height: 70,
        width: 600,
        name: `${name} - Title`,
        type: 'text-annotation',
        extra: {
          value: name,
          fontStyle: {
            margin: 0,
            fontSize: 30,
            color: '#ffffff',
            fontWeight: 'bold',
            textShadow: 'unset',
            fontFamily: 'Inter',
          },
        },
        parentId: id,
        x: 617.50390625,
        y: -67.12890625,
      },
      [`${id}:subtitle`]: {
        layerComponent: 'CanvasTextAnnotationLayer',
        settingSet: {
          General: [
            'CanvasLayerOrderSetting',
            'CanvasLayerGeneralSetting',
            'CanvasLayerBackgroundSetting',
            'CanvasLayerContainerSetting',
          ],
          Font: ['CanvasLayerFontFamilySetting', 'CanvasLayerFontStyleSetting'],
        },
        id: `${id}:subtitle`,
        background: {
          type: 'transparent-background',
        },
        deletable: false,
        draggable: false,
        resizable: true,
        editable: true,
        hideable: true,
        rotatable: true,
        duplicatable: true,
        height: 66,
        width: 792,
        name: `${name} - Subtitle`,
        type: 'text-annotation',
        extra: {
          value: description,
          fontStyle: {
            margin: 0,
            fontSize: 20,
            color: '#c8c8c8',
            textShadow: 'unset',
            fontFamily: 'Inter',
          },
        },
        parentId: id,
        x: 251.90097045898438,
        y: 54.720001220703125,
      },
    },
  },
});

export const GithubStarHistoryAreaChartTemplate4 = (
  id: string,
  name: string,
  description: string,
  data: LineChartData[]
) => ({
  'canvas-background-layer': {
    layerComponent: 'CanvasSquareAnnotationLayer',
    settingSet: {
      General: [
        'CanvasLayerGeneralSetting',
        'CanvasLayerBackgroundSetting',
        'CanvasLayerContainerSetting',
      ],
    },
    id: 'canvas-background-layer',
    name: 'Background',
    height: 932,
    width: 1657,
    x: 0,
    y: 0,
    background: {
      type: 'solid-background',
      value: '#ffffff',
    },
    draggable: false,
    resizable: true,
    deletable: false,
    hideable: false,
    editable: true,
    rotatable: false,
    duplicatable: false,
    type: 'canvas',
    lockAspectRatio: true,
  },
  [id]: {
    layerComponent: 'CanvasLineChartLayer',
    settingSet: {
      General: [
        'CanvasLayerOrderSetting',
        'CanvasLayerGeneralSetting',
        'CanvasLayerBackgroundSetting',
        'CanvasLayerContainerSetting',
      ],
      Chart: [
        'CanvasLayerGeneralChartSetting',
        'CanvasChartAxisSetting',
        'CanvasLayerLineChartSetting',
      ],
    },
    type: 'line-chart',
    background: {
      type: 'solid-background',
      value: '#fefefe',
    },
    cssStyles: {
      borderRadius: 30,
      overflow: 'hidden',
      boxShadow: 'uns',
      borderWidth: 0,
      borderColor: '#001a51',
    },
    height: 768.3333333333334,
    width: 1387.6666666666667,
    x: 11.6015625,
    y: 4.000762939453125,
    id,
    name,
    deletable: true,
    draggable: true,
    resizable: true,
    editable: true,
    rotatable: true,
    hideable: true,
    duplicatable: true,
    extra: {
      labelShown: true,
      lineStrokeStyle: {
        strokeWidth: 2,
        backgroundColor: '#664437',
        color: '#664437',
      },
      editLabelPosition: false,
      editSubjectPosition: false,
      subjectType: 'circle',
      connectorType: 'elbow',
      annotationPosition: {
        x: 645.8104538266227,
        y: 136.15591397849465,
        dx: -150,
        dy: 100,
      },
      annotationTitle: 'New Release v1.0.3',
      annotationTitleStyle: {
        fontSize: 25,
      },
      annotationSubtitle: '',
      annotationSubtitleStyle: {
        fontSize: 20,
      },
      annotationContainerStyle: {
        background: 'white',
        border: '1px solid #e9e9e9',
        boxShadow:
          'rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px',
        borderRadius: 10,
        color: 'rgb(135, 135, 135)',
        fontSize: '0.8em',
        lineHeight: '20px',
        padding: '0 0.4em 0 1em',
        fontWeight: 200,
      },
      annotationContainerWidth: 300,
      columns: {
        xAxis: {
          fieldName: 'X Axis',
          dataType: 'DATE',
        },
        yAxis: {
          fieldName: 'Y Axis',
          dataType: 'NUMBER',
        },
      },
      data,
      areaMode: true,
      axisStyle: {
        fontFamily: 'Inter',
        fontWeight: '700',
        strokeWidth: 3,
        stroke: '#e8e8e8',
      },
      gridColumnsMode: true,
      areaStyle: {
        backgroundColor: '#dfa021',
      },
      lineCurve: true,
    },
    parentId: 'canvas-background-layer',
    childSet: {
      [`${id}:title`]: {
        layerComponent: 'CanvasTextAnnotationLayer',
        settingSet: {
          General: [
            'CanvasLayerOrderSetting',
            'CanvasLayerGeneralSetting',
            'CanvasLayerBackgroundSetting',
            'CanvasLayerContainerSetting',
          ],
          Font: ['CanvasLayerFontFamilySetting', 'CanvasLayerFontStyleSetting'],
        },
        id: `${id}:title`,
        background: {
          type: 'transparent-background',
        },
        deletable: false,
        draggable: false,
        resizable: true,
        editable: true,
        hideable: true,
        rotatable: true,
        duplicatable: true,
        height: 44,
        width: 600,
        name: `${name} - Title`,
        type: 'text-annotation',
        extra: {
          value: name,
          fontStyle: {
            margin: 0,
            fontSize: 30,
            color: 'rgb(0, 0, 0)',
            fontWeight: 'bold',
            textShadow: 'unset',
          },
        },
        parentId: id,
        x: 192.68218994140625,
        y: 13.350006103515625,
      },
      [`${id}:subtitle`]: {
        layerComponent: 'CanvasTextAnnotationLayer',
        settingSet: {
          General: [
            'CanvasLayerOrderSetting',
            'CanvasLayerGeneralSetting',
            'CanvasLayerBackgroundSetting',
            'CanvasLayerContainerSetting',
          ],
          Font: ['CanvasLayerFontFamilySetting', 'CanvasLayerFontStyleSetting'],
        },
        id: `${id}:subtitle`,
        background: {
          type: 'transparent-background',
        },
        deletable: false,
        draggable: false,
        resizable: true,
        editable: true,
        hideable: true,
        rotatable: true,
        duplicatable: true,
        height: 94,
        width: 783,
        name: `${name} - Subtitle`,
        type: 'text-annotation',
        extra: {
          value: description,
          fontStyle: {
            margin: 0,
            fontSize: 20,
            color: 'rgb(135, 135, 135)',
            textShadow: 'unset',
          },
        },
        parentId: id,
        x: 175.8125,
        y: 54.43499755859375,
      },
    },
  },
});

export const GithubStarHistoryAreaChartTemplates = [
  GithubStarHistoryAreaChartTemplate1,
  GithubStarHistoryAreaChartTemplate2,
  GithubStarHistoryAreaChartTemplate3,
  GithubStarHistoryAreaChartTemplate4,
];
